In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
import os
for dirname, _, filenames in os.walk('RTA Dataset.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
data=pd.read_csv('RTA Dataset.csv')

In [ ]:
data.head()


Time Day_of_week Age_band_of_driver Sex_of_driver   Educational_level  \
0  17:02:00      Monday              18-30          Male   Above high school   
1  17:02:00      Monday              31-50          Male  Junior high school   
2  17:02:00      Monday              18-30          Male  Junior high school   
3   1:06:00      Sunday              18-30          Male  Junior high school   
4   1:06:00      Sunday              18-30          Male  Junior high school   

  Vehicle_driver_relation Driving_experience      Type_of_vehicle  \
0                Employee              1-2yr           Automobile   
1                Employee         Above 10yr  Public (> 45 seats)   
2                Employee              1-2yr      Lorry (41?100Q)   
3                Employee             5-10yr  Public (> 45 seats)   
4                Employee              2-5yr                  NaN   

  Owner_of_vehicle Service_year_of_vehicle  ... Vehicle_movement  \
0            Owner              Above 10yr  ...   Going straight   
1            Owner                 5-10yrs  ...   Going straight   
2            Owner                     NaN  ...   Going straight   
3     Governmental                     NaN  ...   Going straight   
4            Owner                 5-10yrs  ...   Going straight   

    Casualty_class Sex_of_casualty Age_band_of_casualty Casualty_severity  \
0               na              na                   na                na   
1               na              na                   na                na   
2  Driver or rider            Male                31-50                 3   
3       Pedestrian          Female                18-30                 3   
4               na              na                   na                na   

  Work_of_casuality Fitness_of_casuality Pedestrian_movement  \
0               NaN                  NaN    Not a Pedestrian   
1               NaN                  NaN    Not a Pedestrian   
2            Driver                  NaN    Not a Pedestrian   
3            Driver               Normal    Not a Pedestrian   
4               NaN                  NaN    Not a Pedestrian   

            Cause_of_accident Accident_severity  
0             Moving Backward     Slight Injury  
1                  Overtaking     Slight Injury  
2   Changing lane to the left    Serious Injury  
3  Changing lane to the right     Slight Injury  
4                  Overtaking     Slight Injury  

[5 rows x 32 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12

In [ ]:
data.describe().T

count      mean       std  min  25%  50%  75%  \
Number_of_vehicles_involved  12316.0  2.040679  0.688790  1.0  2.0  2.0  2.0   
Number_of_casualties         12316.0  1.548149  1.007179  1.0  1.0  1.0  2.0   

                             max  
Number_of_vehicles_involved  7.0  
Number_of_casualties         8.0

In [ ]:
px.pie(data, data['Sex_of_driver'], data['Number_of_casualties'], template='ggplot2',hole=0.5)
px.violin(data,data['Road_surface_type'], data['Number_of_casualties'],color='Accident_severity',template='ggplot2')
px.pie(data,data['Accident_severity'],data['Number_of_casualties'],color='Accident_severity',template='ggplot2',hole=0.5)
px.pie(data,data['Cause_of_accident'],data['Number_of_casualties'],color='Cause_of_accident',template='ggplot2',hole=0.35)
px.histogram(data,data['Day_of_week'],data['Number_of_casualties'],color='Day_of_week',template='ggplot2')
px.histogram(data,data['Educational_level'],data['Number_of_casualties'],color='Educational_level',template='ggplot2')

In [ ]:
px.histogram(data, x=data['Vehicle_driver_relation'], y=data['Number_of_casualties'], color='Vehicle_driver_relation', template='plotly')


In [ ]:
df=data.copy(deep=True)
df.head()

Time Day_of_week Age_band_of_driver Sex_of_driver   Educational_level  \
0  17:02:00      Monday              18-30          Male   Above high school   
1  17:02:00      Monday              31-50          Male  Junior high school   
2  17:02:00      Monday              18-30          Male  Junior high school   
3   1:06:00      Sunday              18-30          Male  Junior high school   
4   1:06:00      Sunday              18-30          Male  Junior high school   

  Vehicle_driver_relation Driving_experience      Type_of_vehicle  \
0                Employee              1-2yr           Automobile   
1                Employee         Above 10yr  Public (> 45 seats)   
2                Employee              1-2yr      Lorry (41?100Q)   
3                Employee             5-10yr  Public (> 45 seats)   
4                Employee              2-5yr                  NaN   

  Owner_of_vehicle Service_year_of_vehicle  ... Vehicle_movement  \
0            Owner              Above 10yr  ...   Going straight   
1            Owner                 5-10yrs  ...   Going straight   
2            Owner                     NaN  ...   Going straight   
3     Governmental                     NaN  ...   Going straight   
4            Owner                 5-10yrs  ...   Going straight   

    Casualty_class Sex_of_casualty Age_band_of_casualty Casualty_severity  \
0               na              na                   na                na   
1               na              na                   na                na   
2  Driver or rider            Male                31-50                 3   
3       Pedestrian          Female                18-30                 3   
4               na              na                   na                na   

  Work_of_casuality Fitness_of_casuality Pedestrian_movement  \
0               NaN                  NaN    Not a Pedestrian   
1               NaN                  NaN    Not a Pedestrian   
2            Driver                  NaN    Not a Pedestrian   
3            Driver               Normal    Not a Pedestrian   
4               NaN                  NaN    Not a Pedestrian   

            Cause_of_accident Accident_severity  
0             Moving Backward     Slight Injury  
1                  Overtaking     Slight Injury  
2   Changing lane to the left    Serious Injury  
3  Changing lane to the right     Slight Injury  
4                  Overtaking     Slight Injury  

[5 rows x 32 columns]

In [ ]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality           

In [ ]:
df.shape

(12316, 32)

In [ ]:
df.drop(['Time','Driving_experience','Type_of_vehicle','Educational_level'],axis=1,inplace=True)
df.drop(['Vehicle_driver_relation','Lanes_or_Medians','Owner_of_vehicle','Area_accident_occured','Road_allignment',
         'Types_of_Junction','Light_conditions','Weather_conditions','Vehicle_movement','Fitness_of_casuality',
        'Vehicle_movement','Age_band_of_driver','Sex_of_driver'],axis=1,inplace=True)
df.drop(['Pedestrian_movement','Cause_of_accident','Work_of_casuality','Road_surface_conditions'],axis=1,inplace=True)
df.drop(['Service_year_of_vehicle','Defect_of_vehicle'],axis=1,inplace=True)
df.dropna(inplace=True)
for i in df.columns:
    if df[i].dtypes== object:
        print(i)
        print(df[i].unique())
        print(df[i].nunique())
        print()

Day_of_week
['Monday' 'Sunday' 'Friday' 'Saturday' 'Thursday' 'Tuesday' 'Wednesday']
7

Road_surface_type
['Asphalt roads' 'Earth roads' 'Asphalt roads with some distress'
 'Gravel roads' 'Other']
5

Type_of_collision
['Collision with roadside-parked vehicles'
 'Vehicle with vehicle collision' 'Collision with roadside objects'
 'Collision with animals' 'Other' 'Rollover' 'Fall from vehicles'
 'Collision with pedestrians' 'With Train' 'Unknown']
10

Casualty_class
['na' 'Driver or rider' 'Pedestrian' 'Passenger']
4

Sex_of_casualty
['na' 'Male' 'Female']
3

Age_band_of_casualty
['na' '31-50' '18-30' 'Under 18' 'Over 51' '5']
6

Casualty_severity
['na' '3' '2' '1']
4

Accident_severity
['Slight Injury' 'Serious Injury' 'Fatal injury']
3



In [ ]:
df.head()


Day_of_week Road_surface_type                        Type_of_collision  \
0      Monday     Asphalt roads  Collision with roadside-parked vehicles   
1      Monday     Asphalt roads           Vehicle with vehicle collision   
2      Monday     Asphalt roads          Collision with roadside objects   
3      Sunday       Earth roads           Vehicle with vehicle collision   
4      Sunday     Asphalt roads           Vehicle with vehicle collision   

   Number_of_vehicles_involved  Number_of_casualties   Casualty_class  \
0                            2                     2               na   
1                            2                     2               na   
2                            2                     2  Driver or rider   
3                            2                     2       Pedestrian   
4                            2                     2               na   

  Sex_of_casualty Age_band_of_casualty Casualty_severity Accident_severity  
0              na                   na                na     Slight Injury  
1              na                   na                na     Slight Injury  
2            Male                31-50                 3    Serious Injury  
3          Female                18-30                 3     Slight Injury  
4              na                   na                na     Slight Injury

In [ ]:

from sklearn.preprocessing import LabelEncoder

l = LabelEncoder()
for col in df.columns:
    if df[col].dtype == object:
        df[col] = l.fit_transform(df[col])

In [ ]:
x=df.drop('Accident_severity',axis=1)
y=df['Accident_severity']
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.30)
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler(feature_range=(0,1))
xtrain=mms.fit_transform(xtrain)
xtest=mms.fit_transform(xtest)
xtrain=pd.DataFrame(xtrain)
xtest=pd.DataFrame(xtest)
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
rf = RandomForestClassifier()
rf.fit(xtrain,ytrain)

ypred=rf.predict(xtest)

print('-----------------------------------------------------------------------------------------------------------------------')
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,recall_score,f1_score,precision_score

print('CONFUSION MATRIX :\n',confusion_matrix(ytest,ypred))
print('CLASSIFICATION REPORT :\n',classification_report(ytest,ypred))
print('ACCURACY :',round(accuracy_score(ytest,ypred),2))
print('PRECISION :',round(precision_score(ytest,ypred,average='weighted'),2))
print('RECALL :',round(recall_score(ytest,ypred,average='weighted'),2))
print('F1 :',round(f1_score(ytest,ypred,average='weighted'),2))
print()

-----------------------------------------------------------------------------------------------------------------------
CONFUSION MATRIX :
 [[   3    1   48]
 [   6   46  484]
 [  14   98 2898]]
CLASSIFICATION REPORT :
               precision    recall  f1-score   support

           0       0.13      0.06      0.08        52
           1       0.32      0.09      0.14       536
           2       0.84      0.96      0.90      3010

    accuracy                           0.82      3598
   macro avg       0.43      0.37      0.37      3598
weighted avg       0.76      0.82      0.77      3598

ACCURACY : 0.82
PRECISION : 0.76
RECALL : 0.82
F1 : 0.77

